# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='tagprofile',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='core.TagProfile'),
        ),
    ]
